// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKeV2um6JnlfE4TyvxSAv3JldfTKi3Us',
    appId: '1:371840185734:web:2e500c445168deb1d1a807',
    messagingSenderId: '371840185734',
    projectId: 'graduation-project-bumgd17',
    authDomain: 'graduation-project-bumgd17.firebaseapp.com',
    storageBucket: 'graduation-project-bumgd17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7hgjahxcQkUsBAlB6MEi9Mjt14MZe5A',
    appId: '1:371840185734:android:9760fefd08d5aa98d1a807',
    messagingSenderId: '371840185734',
    projectId: 'graduation-project-bumgd17',
    storageBucket: 'graduation-project-bumgd17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmm1tILa0jYf2GAxXinC6RXpKW6WNLxgE',
    appId: '1:371840185734:ios:85c9a894f85875afd1a807',
    messagingSenderId: '371840185734',
    projectId: 'graduation-project-bumgd17',
    storageBucket: 'graduation-project-bumgd17.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmm1tILa0jYf2GAxXinC6RXpKW6WNLxgE',
    appId: '1:371840185734:ios:85c9a894f85875afd1a807',
    messagingSenderId: '371840185734',
    projectId: 'graduation-project-bumgd17',
    storageBucket: 'graduation-project-bumgd17.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAKeV2um6JnlfE4TyvxSAv3JldfTKi3Us',
    appId: '1:371840185734:web:f8615d0375319248d1a807',
    messagingSenderId: '371840185734',
    projectId: 'graduation-project-bumgd17',
    authDomain: 'graduation-project-bumgd17.firebaseapp.com',
    storageBucket: 'graduation-project-bumgd17.firebasestorage.app',
  );
}
